### ISSUE TITLE
unable to mount it

### ISSUE THREAD

**Issue by coolternet** [owl1n/vue-translations#3]
hello. I'm new on VueJS and i'm trying to use your plugin.

I'm getting this error :

index.js:27 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'setup' of undefined"
(found in <Root>)

and i have follow every installation step

**Comment by owl1n** [comment]
hi, man
let me see your code of component, please

**Comment by HorakAles** [comment]
I get same exact error when trying to use this package with Laravel and Vue.

**Comment by HorakAles** [comment]
I get same exact error when trying to use this package with Laravel and Vue.
